Establish a relationship between:
1. price and house size
2. price and views
3. price and condition

Overall Questions:
1. What is the biggest influence on price?
2. Are more expensive houses an easier sell?

Increasing Views:
1. Views vs Price
2. Views vs Grade
3. Views cs condition

House Specs:
1. Size of living space vs Size of lot
2. Floors vs living space
3. House condition vs grade
4. How recently revovated vs views

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [2]:
df = pd.read_csv('kc_house_data.csv')
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,10/13/2014,221900.0,3,1.00,1180,5650,1.0,NaN,0.0,...,7,1180,0.0,1955,0.0,98178,47.5112,-122.257,1340,5650
1,6414100192,12/9/2014,538000.0,3,2.25,2570,7242,2.0,0.0,0.0,...,7,2170,400.0,1951,1991.0,98125,47.7210,-122.319,1690,7639
2,5631500400,2/25/2015,180000.0,2,1.00,770,10000,1.0,0.0,0.0,...,6,770,0.0,1933,NaN,98028,47.7379,-122.233,2720,8062
3,2487200875,12/9/2014,604000.0,4,3.00,1960,5000,1.0,0.0,0.0,...,7,1050,910.0,1965,0.0,98136,47.5208,-122.393,1360,5000
4,1954400510,2/18/2015,510000.0,3,2.00,1680,8080,1.0,0.0,0.0,...,8,1680,0.0,1987,0.0,98074,47.6168,-122.045,1800,7503

In [3]:
display(df.info())
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 21 columns):
id               21597 non-null int64
date             21597 non-null object
price            21597 non-null float64
bedrooms         21597 non-null int64
bathrooms        21597 non-null float64
sqft_living      21597 non-null int64
sqft_lot         21597 non-null int64
floors           21597 non-null float64
waterfront       19221 non-null float64
view             21534 non-null float64
condition        21597 non-null int64
grade            21597 non-null int64
sqft_above       21597 non-null int64
sqft_basement    21597 non-null object
yr_built         21597 non-null int64
yr_renovated     17755 non-null float64
zipcode          21597 non-null int64
lat              21597 non-null float64
long             21597 non-null float64
sqft_living15    21597 non-null int64
sqft_lot15       21597 non-null int64
dtypes: float64(8), int64(11), object(2)
memory usage: 3.5+ MB

None

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.159700e+04,2.159700e+04,21597.000000,21597.000000,21597.000000,2.159700e+04,21597.000000,19221.000000,21534.000000,21597.000000,21597.000000,21597.000000,21597.000000,17755.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000
mean,4.580474e+09,5.402966e+05,3.373200,2.115826,2080.321850,1.509941e+04,1.494096,0.007596,0.233863,3.409825,7.657915,1788.596842,1970.999676,83.636778,98077.951845,47.560093,-122.213982,1986.620318,12758.283512
std,2.876736e+09,3.673681e+05,0.926299,0.768984,918.106125,4.141264e+04,0.539683,0.086825,0.765686,0.650546,1.173200,827.759761,29.375234,399.946414,53.513072,0.138552,0.140724,685.230472,27274.441950
min,1.000102e+06,7.800000e+04,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,3.000000,370.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.220000e+05,3.000000,1.750000,1430.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,1951.000000,0.000000,98033.000000,47.471100,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,1975.000000,0.000000,98065.000000,47.571800,-122.231000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068500e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [5]:
df.corr()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,1.000000,-0.016772,0.001150,0.005162,-0.012241,-0.131911,0.018608,-0.004176,0.011592,-0.023803,0.008188,-0.010799,0.021617,-0.012010,-0.008211,-0.001798,0.020672,-0.002701,-0.138557
price,-0.016772,1.000000,0.308787,0.525906,0.701917,0.089876,0.256804,0.276295,0.395734,0.036056,0.667951,0.605368,0.053953,0.129599,-0.053402,0.306692,0.022036,0.585241,0.082845
bedrooms,0.001150,0.308787,1.000000,0.514508,0.578212,0.032471,0.177944,-0.002386,0.078523,0.026496,0.356563,0.479386,0.155670,0.018495,-0.154092,-0.009951,0.132054,0.393406,0.030690
bathrooms,0.005162,0.525906,0.514508,1.000000,0.755758,0.088373,0.502582,0.067282,0.186451,-0.126479,0.665838,0.686668,0.507173,0.051050,-0.204786,0.024280,0.224903,0.569884,0.088303
sqft_living,-0.012241,0.701917,0.578212,0.755758,1.000000,0.173453,0.353953,0.110230,0.282532,-0.059445,0.762779,0.876448,0.318152,0.055660,-0.199802,0.052155,0.241214,0.756402,0.184342
sqft_lot,-0.131911,0.089876,0.032471,0.088373,0.173453,1.000000,-0.004814,0.023143,0.075298,-0.008830,0.114731,0.184139,0.052946,0.004513,-0.129586,-0.085514,0.230227,0.144763,0.718204
floors,0.018608,0.256804,0.177944,0.502582,0.353953,-0.004814,1.000000,0.021883,0.028436,-0.264075,0.458794,0.523989,0.489193,0.003535,-0.059541,0.049239,0.125943,0.280102,-0.010722
waterfront,-0.004176,0.276295,-0.002386,0.067282,0.110230,0.023143,0.021883,1.000000,0.406654,0.017642,0.087383,0.075463,-0.026079,0.087244,0.031057,-0.012772,-0.039864,0.088860,0.032002
view,0.011592,0.395734,0.078523,0.186451,0.282532,0.075298,0.028436,0.406654,1.000000,0.045735,0.249727,0.166299,-0.054564,0.100964,0.085277,0.006141,-0.077894,0.279561,0.073332
condition,-0.023803,0.036056,0.026496,-0.126479,-0.059445,-0.008830,-0.264075,0.017642,0.045735,1.000000,-0.146896,-0.158904,-0.361592,-0.061858,0.002888,-0.015102,-0.105877,-0.093072,-0.003126
grade,0.008188,0.667951,0.356563,0.665838,0.762779,0.114731,0.458794,0.087383,0.249727,-0.146896,1.000000,0.756073,0.447865,0.016669,-0.185771,0.113575,0.200341,0.713867,0.120981
sqft_above,-0.010799,0.605368,0.479386,0.686668,0.876448,0.184139,0.523989,0.075463,0.166299,-0.158904,0.756073,1.000000,0.424037,0.022137,-0.261570,-0.001199,0.344842,0.731767,0.195077
yr_built,0.021617,0.053953,0.155670,0.507173,0.318152,0.052946,0.489193,-0.026079,-0.054564,-0.361592,0.447865,0.424037,1.000000,-0.225209,-0.347210,-0.148370,0.409993,0.326377,0.070777
yr_renovated,-0.012010,0.129599,0.018495,0.051050,0.055660,0.004513,0.003535,0.087244,0.100964,-0.061858,0.016669,0.022137,-0.225209,1.000000,0.069846,0.032145,-0.072156,-0.000247,0.003852
zipcode,-0.008211,-0.053402,-0.154092,-0.204786,-0.199802,-0.129586,-0.059541,0.031057,0.085277,0.002888,-0.185771,-0.261570,-0.347210,0.069846,1.000000,0.266742,-0.564259,-0.279299,-0.147294
lat,-0.001798,0.306692,-0.009951,0.024280,0.052155,-0.085514,0.049239,-0.012772,0.006141,-0.015102,0.113575,-0.001199,-0.148370,0.032145,0.266742,1.000000,-0.135371,0.048679,-0.086139
long,0.020672,0.022036,0.132054,0.224903,0.241214,0.230227,0.125943,-0.039864,-0.077894,-0.105877,0.200341,0.344842,0.409993,-0.072156,-0.564259,-0.135371,1.000000,0.335626,0.255586
sqft_living15,-0.002701,0.585241,0.393406,0.569884,0.756402,0.144763,0.280102,0.088860,0.279561,-0.093072,0.713867,0.731767,0.326377,-0.000247,-0.279299,0.048679,0.335626,1.000000,0.183515
sqft_lot15,-0.138557,0.082845,0.030690,0.088303,0.184342,0.718204,-0.010722,0.032002,0.073332,-0.003126,0.120981,0.195077,0.070777,0.003852,-0.147294,-0.086139,0.255586,0.183515,1.000000

In [7]:
df.isna().any()

id               False
date             False
price            False
bedrooms         False
bathrooms        False
sqft_living      False
sqft_lot         False
floors           False
waterfront        True
view              True
condition        False
grade            False
sqft_above       False
sqft_basement    False
yr_built         False
yr_renovated      True
zipcode          False
lat              False
long             False
sqft_living15    False
sqft_lot15       False
dtype: bool

In [8]:
df.isna().sum()

id                  0
date                0
price               0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2376
view               63
condition           0
grade               0
sqft_above          0
sqft_basement       0
yr_built            0
yr_renovated     3842
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [9]:
df.isnull().sum()

id                  0
date                0
price               0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2376
view               63
condition           0
grade               0
sqft_above          0
sqft_basement       0
yr_built            0
yr_renovated     3842
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [17]:
df.drop(columns='waterfront', axis=1, inplace= True)

In [18]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,10/13/2014,221900.0,3,1.00,1180,5650,1.0,0.0,3,7,1180,0.0,1955,0.0,98178,47.5112,-122.257,1340,5650
1,6414100192,12/9/2014,538000.0,3,2.25,2570,7242,2.0,0.0,3,7,2170,400.0,1951,1991.0,98125,47.7210,-122.319,1690,7639
2,5631500400,2/25/2015,180000.0,2,1.00,770,10000,1.0,0.0,3,6,770,0.0,1933,NaN,98028,47.7379,-122.233,2720,8062
3,2487200875,12/9/2014,604000.0,4,3.00,1960,5000,1.0,0.0,5,7,1050,910.0,1965,0.0,98136,47.5208,-122.393,1360,5000
4,1954400510,2/18/2015,510000.0,3,2.00,1680,8080,1.0,0.0,3,8,1680,0.0,1987,0.0,98074,47.6168,-122.045,1800,7503
5,7237550310,5/12/2014,1230000.0,4,4.50,5420,101930,1.0,0.0,3,11,3890,1530.0,2001,0.0,98053,47.6561,-122.005,4760,101930
6,1321400060,6/27/2014,257500.0,3,2.25,1715,6819,2.0,0.0,3,7,1715,?,1995,0.0,98003,47.3097,-122.327,2238,6819
7,2008000270,1/15/2015,291850.0,3,1.50,1060,9711,1.0,NaN,3,7,1060,0.0,1963,0.0,98198,47.4095,-122.315,1650,9711
8,2414600126,4/15/2015,229500.0,3,1.00,1780,7470,1.0,0.0,3,7,1050,730.0,1960,0.0,98146,47.5123,-122.337,1780,8113
9,3793500160,3/12/2015,323000.0,3,2.50,1890,6560,2.0,0.0,3,7,1890,0.0,2003,0.0,98038,47.3684,-122.031,2390,7570
10,1736800520,4/3/2015,662500.0,3,2.50,3560,9796,1.0,0.0,3,8,1860,1700.0,1965,0.0,98007,47.6007,-122.145,2210,8925
11,9212900260,5/27/2014,468000.0,2,1.00,1160,6000,1.0,0.0,4,7,860,300.0,1942,0.0,98115,47.6900,-122.292,1330,6000
12,114101516,5/28/2014,310000.0,3,1.00,1430,19901,1.5,0.0,4,7,1430,0.0,1927,NaN,98028,47.7558,-122.229,1780,12697
13,6054650070,10/7/2014,400000.0,3,1.75,1370,9680,1.0,0.0,4,7,1370,0.0,1977,0.0,98074,47.6127,-122.045,1370,10208
14,1175000570,3/12/2015,530000.0,5,2.00,1810,4850,1.5,0.0,3,7,1810,0.0,1900,0.0,98107,47.6700,-122.394,1360,4850
15,9297300055,1/24/2015,650000.0,4,3.00,2950,5000,2.0,3.0,3,9,1980,970.0,1979,0.0,98126,47.5714,-122.375,2140,4000
16,1875500060,7/31/2014,395000.0,3,2.00,1890,14040,2.0,0.0,3,7,1890,0.0,1994,0.0,98019,47.7277,-121.962,1890,14018
17,6865200140,5/29/2014,485000.0,4,1.00,1600,4300,1.5,0.0,4,7,1600,0.0,1916,0.0,98103,47.6648,-122.343,1610,4300
18,16000397,12/5/2014,189000.0,2,1.00,1200,9850,1.0,0.0,4,7,1200,?,1921,0.0,98002,47.3089,-122.210,1060,5095
19,7983200060,4/24/2015,230000.0,3,1.00,1250,9774,1.0,0.0,4,7,1250,0.0,1969,0.0,98003,47.3343,-122.306,1280,8850
20,6300500875,5/14/2014,385000.0,4,1.75,1620,4980,1.0,0.0,4,7,860,760.0,1947,0.0,98133,47.7025,-122.341,1400,4980
21,2524049179,8/26/2014,2000000.0,3,2.75,3050,44867,1.0,4.0,3,9,2330,720.0,1968,0.0,98040,47.5316,-122.233,4110,20336
22,7137970340,7/3/2014,285000.0,5,2.50,2270,6300,2.0,0.0,3,8,2270,0.0,1995,0.0,98092,47.3266,-122.169,2240,7005
23,8091400200,5/16/2014,252700.0,2,1.50,1070,9643,1.0,0.0,3,7,1070,0.0,1985,NaN,98030,47.3533,-122.166,1220,8386
24,3814700200,11/20/2014,329000.0,3,2.25,2450,6500,2.0,0.0,4,8,2450,0.0,1985,0.0,98030,47.3739,-122.172,2200,6865
25,1202000200,11/3/2014,233000.0,3,2.00,1710,4697,1.5,0.0,5,6,1710,0.0,1941,0.0,98002,47.3048,-122.218,1030,4705
26,1794500383,6/26/2014,937000.0,3,1.75,2450,2691,2.0,0.0,3,8,1750,700.0,1915,NaN,98119,47.6386,-122.360,1760,3573
27,3303700376,12/1/2014,667000.0,3,1.00,1400,1581,1.5,0.0,5,8,1400,0.0,1909,0.0,98112,47.6221,-122.314,1860,3861
28,5101402488,6/24/2014,438000.0,3,1.75,1520,6380,1.0,0.0,3,7,790,730.0,1948,NaN,98115,47.6950,-122.304,1520,6235
29,1873100390,3/2/2015,719000.0,4,2.50,2570,7173,2.0,0.0,3,8,2570,0.0,2005,0.0,98052,47.7073,-122.110,2630,6026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21567,2025049203,6/10/2014,399950.0,2,1.00,710,1157,2.0,0.0,4,7,710,0.0,1943,0.0,98102,47.6413,-122.329,1370,1173
21568,952006823,12/2/2014,380000.0,3,2.50,1260,900,2.0,0.0,3,7,940,320.0,2007,0.0,98116,47.5621,-122.384,1310,1415
21569,3832050760,8/28/2014,270000.0,3,2.50,1870,5000,2.0,0.0,3,7,1870,0.0,2009,0.0,98042,47.3339,-122.055,2170,5399
21570,2767604724,10/15/2014,505000.0,2,2.50,1430,1201,3.0,0.0,3,8,1430,0.0,2009,0.0,98107,47.6707,-122.381,1430,1249
21571,6632300207,3/5/2015,385000.0,3,2.50,1520,1488,3.0,0.0,3,8,1520,0.0,2006,0.0,98125,47.7337,-122.309,1520,1497
21572,2767600688,11/13/2014,414500.0,2,1.50,1210,1278,2.0,0.0,3,8,1020,190.0,2007,0.0,98117,47.6756,-122.375,1210,1118
21573,7570050450,9/10/2014,347500.0,3,2.50,2540,4760,2.0,0.0,3,8,2540,0.0,2010,0.0,98038,47.3452,-122.022,2540,4571
21574,7430200100,5/14/2014,1220000.0,4,3.50,4910,9444,1.5,0.0,3,11,3110,1800.0,2007,0.0,98074,47.6502,-122.066,4560,11063
21575,4140940150,10/2/2014,572000.0,4,2.75,2770,3852,2.0,0.0,3,8,2770,0.0,2014,NaN,98178,47.5001,-122.232,1810,5641
21576,1931300412,4/16/2015,475000.0,3,2.25,1190,1200,3.0,0.0,3,8,1190,0.0,2008,NaN,98103,47.6542,-122.346,1180,1224
21577,8672200110,3/17/2015,1090000.0,5,3.75,4170,8142,2.0,2.0,3,10,4170,0.0,2006,NaN,98056,47.5354,-122.181,3030,7980
21578,5087900040,10/17/2014,350000.0,4,2.75,2500,5995,2.0,0.0,3,8,2500,0.0,2008,0.0,98042,47.3749,-122.107,2530,5988
21579,1972201967,10/31/2014,520000.0,2,2.25,1530,981,3.0,0.0,3,8,1480,50.0,2006,NaN,98103,47.6533,-122.346,1530,1282
21580,7502800100,8/13/2014,679950.0,5,2.75,3600,9437,2.0,0.0,3,9,3600,0.0,2014,0.0,98059,47.4822,-122.131,3550,9421
21581,191100405,4/21/2015,1580000.0,4,3.25,3410,10125,2.0,0.0,3,10,3410,?,2007,NaN,98040,47.5653,-122.223,2290,10125
21582,8956200760,10/13/2014,541800.0,4,2.50,3118,7866,2.0,2.0,3,9,3118,0.0,2014,0.0,98001,47.2931,-122.264,2673,6500
21583,7202300110,9/15/2014,810000.0,4,3.00,3990,7838,2.0,0.0,3,9,3990,0.0,2003,NaN,98053,47.6857,-122.046,3370,6814
21584,249000205,10/15/2014,1540000.0,5,3.75,4470,8088,2.0,0.0,3,11,4470,0.0,2008,0.0,98004,47.6321,-122.200,2780,8964
21585,5100403806,4/7/2015,467000.0,3,2.50,1425,1179,3.0,0.0,3,8,1425,0.0,2008,0.0,98125,47.6963,-122.318,1285,1253
21586,844000965,6/26/2014,224000.0,3,1.75,1500,11968,1.0,0.0,3,6,1500,0.0,2014,0.0,98010,47.3095,-122.002,1320,11303
21587,7852140040,8/25/2014,507250.0,3,2.50,2270,5536,2.0,0.0,3,8,2270,0.0,2003,0.0,98065,47.5389,-121.881,2270,5731
21588,9834201367,1/26/2015,429000.0,3,2.00,1490,1126,3.0,0.0,3,8,1490,0.0,2014,0.0,98144,47.5699,-122.288,1400,1230
21589,3448900210,10/14/2014,610685.0,4,2.50,2520,6023,2.0,NaN,3,9,2520,0.0,2014,0.0,98056,47.5137,-122.167,2520,6023
21590,7936000429,3/26/2015,1010000.0,4,3.50,3510,7200,2.0,0.0,3,9,2600,910.0,2009,0.0,98136,47.5537,-122.398,2050,6200
21591,2997800021,2/19/2015,475000.0,3,2.50,1310,1294,2.0,0.0,3,8,1180,130.0,2008,0.0,98116,47.5773,-122.409,1330,1265
21592,263000018,5/21/2014,360000.0,3,2.50,1530,1131,3.0,0.0,3,8,1530,0.0,2009,0.0,98103,47.6993,-122.346,1530,1509
21593,6600060120,2/23/2015,400000.0,4,2.50,2310,5813,2.0,0.0,3,8,2310,0.0,2014,0.0,98146,47.5107,-122.362,1830,7200
21594,1523300141,6/23/2014,402101.0,2,0.75,1020,1350,2.0,0.0,3,7,1020,0.0,2009,0.0,98144,47.5944,-122.299,1020,2007
21595,291310100,1/16/2015,400000.0,3,2.50,1600,2388,2.0,0.0,3,8,1600,0.0,2004,0.0,98027,47.5345,-122.069,1410,1287
21596,1523300157,10/15/2014,325000.0,2,0.75,1020,1076,2.0,0.0,3,7,1020,0.0,2008,0.0,98144,47.5941,-122.299,1020,1357

In [38]:
df['date'] = pd.to_datetime(df['date'])

In [39]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0.0,3,7,1180,0.0,1955,0.0,98178,47.5112,-122.257,1340,5650
1,6414100192,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0.0,3,7,2170,400.0,1951,1991.0,98125,47.7210,-122.319,1690,7639
2,5631500400,2015-02-25,180000.0,2,1.00,770,10000,1.0,0.0,3,6,770,0.0,1933,NaN,98028,47.7379,-122.233,2720,8062
3,2487200875,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0.0,5,7,1050,910.0,1965,0.0,98136,47.5208,-122.393,1360,5000
4,1954400510,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0.0,3,8,1680,0.0,1987,0.0,98074,47.6168,-122.045,1800,7503
5,7237550310,2014-05-12,1230000.0,4,4.50,5420,101930,1.0,0.0,3,11,3890,1530.0,2001,0.0,98053,47.6561,-122.005,4760,101930
6,1321400060,2014-06-27,257500.0,3,2.25,1715,6819,2.0,0.0,3,7,1715,?,1995,0.0,98003,47.3097,-122.327,2238,6819
7,2008000270,2015-01-15,291850.0,3,1.50,1060,9711,1.0,NaN,3,7,1060,0.0,1963,0.0,98198,47.4095,-122.315,1650,9711
8,2414600126,2015-04-15,229500.0,3,1.00,1780,7470,1.0,0.0,3,7,1050,730.0,1960,0.0,98146,47.5123,-122.337,1780,8113
9,3793500160,2015-03-12,323000.0,3,2.50,1890,6560,2.0,0.0,3,7,1890,0.0,2003,0.0,98038,47.3684,-122.031,2390,7570
10,1736800520,2015-04-03,662500.0,3,2.50,3560,9796,1.0,0.0,3,8,1860,1700.0,1965,0.0,98007,47.6007,-122.145,2210,8925
11,9212900260,2014-05-27,468000.0,2,1.00,1160,6000,1.0,0.0,4,7,860,300.0,1942,0.0,98115,47.6900,-122.292,1330,6000
12,114101516,2014-05-28,310000.0,3,1.00,1430,19901,1.5,0.0,4,7,1430,0.0,1927,NaN,98028,47.7558,-122.229,1780,12697
13,6054650070,2014-10-07,400000.0,3,1.75,1370,9680,1.0,0.0,4,7,1370,0.0,1977,0.0,98074,47.6127,-122.045,1370,10208
14,1175000570,2015-03-12,530000.0,5,2.00,1810,4850,1.5,0.0,3,7,1810,0.0,1900,0.0,98107,47.6700,-122.394,1360,4850
15,9297300055,2015-01-24,650000.0,4,3.00,2950,5000,2.0,3.0,3,9,1980,970.0,1979,0.0,98126,47.5714,-122.375,2140,4000
16,1875500060,2014-07-31,395000.0,3,2.00,1890,14040,2.0,0.0,3,7,1890,0.0,1994,0.0,98019,47.7277,-121.962,1890,14018
17,6865200140,2014-05-29,485000.0,4,1.00,1600,4300,1.5,0.0,4,7,1600,0.0,1916,0.0,98103,47.6648,-122.343,1610,4300
18,16000397,2014-12-05,189000.0,2,1.00,1200,9850,1.0,0.0,4,7,1200,?,1921,0.0,98002,47.3089,-122.210,1060,5095
19,7983200060,2015-04-24,230000.0,3,1.00,1250,9774,1.0,0.0,4,7,1250,0.0,1969,0.0,98003,47.3343,-122.306,1280,8850
20,6300500875,2014-05-14,385000.0,4,1.75,1620,4980,1.0,0.0,4,7,860,760.0,1947,0.0,98133,47.7025,-122.341,1400,4980
21,2524049179,2014-08-26,2000000.0,3,2.75,3050,44867,1.0,4.0,3,9,2330,720.0,1968,0.0,98040,47.5316,-122.233,4110,20336
22,7137970340,2014-07-03,285000.0,5,2.50,2270,6300,2.0,0.0,3,8,2270,0.0,1995,0.0,98092,47.3266,-122.169,2240,7005
23,8091400200,2014-05-16,252700.0,2,1.50,1070,9643,1.0,0.0,3,7,1070,0.0,1985,NaN,98030,47.3533,-122.166,1220,8386
24,3814700200,2014-11-20,329000.0,3,2.25,2450,6500,2.0,0.0,4,8,2450,0.0,1985,0.0,98030,47.3739,-122.172,2200,6865
25,1202000200,2014-11-03,233000.0,3,2.00,1710,4697,1.5,0.0,5,6,1710,0.0,1941,0.0,98002,47.3048,-122.218,1030,4705
26,1794500383,2014-06-26,937000.0,3,1.75,2450,2691,2.0,0.0,3,8,1750,700.0,1915,NaN,98119,47.6386,-122.360,1760,3573
27,3303700376,2014-12-01,667000.0,3,1.00,1400,1581,1.5,0.0,5,8,1400,0.0,1909,0.0,98112,47.6221,-122.314,1860,3861
28,5101402488,2014-06-24,438000.0,3,1.75,1520,6380,1.0,0.0,3,7,790,730.0,1948,NaN,98115,47.6950,-122.304,1520,6235
29,1873100390,2015-03-02,719000.0,4,2.50,2570,7173,2.0,0.0,3,8,2570,0.0,2005,0.0,98052,47.7073,-122.110,2630,6026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21567,2025049203,2014-06-10,399950.0,2,1.00,710,1157,2.0,0.0,4,7,710,0.0,1943,0.0,98102,47.6413,-122.329,1370,1173
21568,952006823,2014-12-02,380000.0,3,2.50,1260,900,2.0,0.0,3,7,940,320.0,2007,0.0,98116,47.5621,-122.384,1310,1415
21569,3832050760,2014-08-28,270000.0,3,2.50,1870,5000,2.0,0.0,3,7,1870,0.0,2009,0.0,98042,47.3339,-122.055,2170,5399
21570,2767604724,2014-10-15,505000.0,2,2.50,1430,1201,3.0,0.0,3,8,1430,0.0,2009,0.0,98107,47.6707,-122.381,1430,1249
21571,6632300207,2015-03-05,385000.0,3,2.50,1520,1488,3.0,0.0,3,8,1520,0.0,2006,0.0,98125,47.7337,-122.309,1520,1497
21572,2767600688,2014-11-13,414500.0,2,1.50,1210,1278,2.0,0.0,3,8,1020,190.0,2007,0.0,98117,47.6756,-122.375,1210,1118
21573,7570050450,2014-09-10,347500.0,3,2.50,2540,4760,2.0,0.0,3,8,2540,0.0,2010,0.0,98038,47.3452,-122.022,2540,4571
21574,7430200100,2014-05-14,1220000.0,4,3.50,4910,9444,1.5,0.0,3,11,3110,1800.0,2007,0.0,98074,47.6502,-122.066,4560,11063
21575,4140940150,2014-10-02,572000.0,4,2.75,2770,3852,2.0,0.0,3,8,2770,0.0,2014,NaN,98178,47.5001,-122.232,1810,5641
21576,1931300412,2015-04-16,475000.0,3,2.25,1190,1200,3.0,0.0,3,8,1190,0.0,2008,NaN,98103,47.6542,-122.346,1180,1224
21577,8672200110,2015-03-17,1090000.0,5,3.75,4170,8142,2.0,2.0,3,10,4170,0.0,2006,NaN,98056,47.5354,-122.181,3030,7980
21578,5087900040,2014-10-17,350000.0,4,2.75,2500,5995,2.0,0.0,3,8,2500,0.0,2008,0.0,98042,47.3749,-122.107,2530,5988
21579,1972201967,2014-10-31,520000.0,2,2.25,1530,981,3.0,0.0,3,8,1480,50.0,2006,NaN,98103,47.6533,-122.346,1530,1282
21580,7502800100,2014-08-13,679950.0,5,2.75,3600,9437,2.0,0.0,3,9,3600,0.0,2014,0.0,98059,47.4822,-122.131,3550,9421
21581,191100405,2015-04-21,1580000.0,4,3.25,3410,10125,2.0,0.0,3,10,3410,?,2007,NaN,98040,47.5653,-122.223,2290,10125
21582,8956200760,2014-10-13,541800.0,4,2.50,3118,7866,2.0,2.0,3,9,3118,0.0,2014,0.0,98001,47.2931,-122.264,2673,6500
21583,7202300110,2014-09-15,810000.0,4,3.00,3990,7838,2.0,0.0,3,9,3990,0.0,2003,NaN,98053,47.6857,-122.046,3370,6814
21584,249000205,2014-10-15,1540000.0,5,3.75,4470,8088,2.0,0.0,3,11,4470,0.0,2008,0.0,98004,47.6321,-122.200,2780,8964
21585,5100403806,2015-04-07,467000.0,3,2.50,1425,1179,3.0,0.0,3,8,1425,0.0,2008,0.0,98125,47.6963,-122.318,1285,1253
21586,844000965,2014-06-26,224000.0,3,1.75,1500,11968,1.0,0.0,3,6,1500,0.0,2014,0.0,98010,47.3095,-122.002,1320,11303
21587,7852140040,2014-08-25,507250.0,3,2.50,2270,5536,2.0,0.0,3,8,2270,0.0,2003,0.0,98065,47.5389,-121.881,2270,5731
21588,9834201367,2015-01-26,429000.0,3,2.00,1490,1126,3.0,0.0,3,8,1490,0.0,2014,0.0,98144,47.5699,-122.288,1400,1230
21589,3448900210,2014-10-14,610685.0,4,2.50,2520,6023,2.0,NaN,3,9,2520,0.0,2014,0.0,98056,47.5137,-122.167,2520,6023
21590,7936000429,2015-03-26,1010000.0,4,3.50,3510,7200,2.0,0.0,3,9,2600,910.0,2009,0.0,98136,47.5537,-122.398,2050,6200
21591,2997800021,2015-02-19,475000.0,3,2.50,1310,1294,2.0,0.0,3,8,1180,130.0,2008,0.0,98116,47.5773,-122.409,1330,1265
21592,263000018,2014-05-21,360000.0,3,2.50,1530,1131,3.0,0.0,3,8,1530,0.0,2009,0.0,98103,47.6993,-122.346,1530,1509
21593,6600060120,2015-02-23,400000.0,4,2.50,2310,5813,2.0,0.0,3,8,2310,0.0,2014,0.0,98146,47.5107,-122.362,1830,7200
21594,1523300141,2014-06-23,402101.0,2,0.75,1020,1350,2.0,0.0,3,7,1020,0.0,2009,0.0,98144,47.5944,-122.299,1020,2007
21595,291310100,2015-01-16,400000.0,3,2.50,1600,2388,2.0,0.0,3,8,1600,0.0,2004,0.0,98027,47.5345,-122.069,1410,1287
21596,1523300157,2014-10-15,325000.0,2,0.75,1020,1076,2.0,0.0,3,7,1020,0.0,2008,0.0,98144,47.5941,-122.299,1020,1357